version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mindset_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mindset-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mindset_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mindset-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      BACKEND_URL: /api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mindset-network
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    networks:
      - mindset-network
    restart: unless-stopped

networks:
  mindset-network:
    driver: bridge

volumes:
  postgres_data:
  nginx_logs: