version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mindset_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - mindset-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mindset_db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mindset-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      BACKEND_URL: /api
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mindset-network
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt:/var/www/certbot
      - ./certbot/www:/var/www/certbot
      - ./nginx_logs:/var/log/nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - mindset-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./letsencrypt-logs:/var/log/letsencrypt
    entrypoint: >
      sh -c "certbot certonly
             --webroot -w /var/www/certbot
             -d schoolmindset.ru -d www.schoolmindset.ru
             --email Greg5320123@gmail.com
             --agree-tos
             --no-eff-email
             --force-renewal"

  certbot-renew:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do
               certbot renew --webroot -w /var/www/certbot && nginx -s reload;
               sleep 12h;
             done"

networks:
  mindset-network:
    driver: bridge

volumes:
  postgres_data:
  nginx_logs:
